replicaCount: 1

deployment:
  annotations: {}
  environment: prod

image:
  repository: ghcr.io/godsvictory/app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "false"
  className: nginx
  path: /
  hosts:
    - node-prod.home

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
