replicaCount: 2
deployment:
  annotations: {}
  environment: dev
image:
  repository: ghcr.io/godsvictory/app
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  annotations: {}
  className: nginx
  path: /
  hosts:
    - node-dev.home
resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
